package ZES.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ActCommandHandler = 0;
  public static final int AggregateRoot = 1;
  public static final int Command = 2;
  public static final int CommandHandler = 3;
  public static final int CreateCommand = 4;
  public static final int CreateCommandHandler = 5;
  public static final int DomainClass = 6;
  public static final int Target = 7;
  public static final int TargetCommand = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xabe666e11ee143feL, 0x93c4703403beeec8L);
    builder.put(0x7890b7ca7815b52bL, ActCommandHandler);
    builder.put(0x7890b7ca78161258L, AggregateRoot);
    builder.put(0x45a819bfd46f2e3aL, Command);
    builder.put(0x7890b7ca7815b026L, CommandHandler);
    builder.put(0x7890b7ca78198eb0L, CreateCommand);
    builder.put(0x7890b7ca7815b52cL, CreateCommandHandler);
    builder.put(0x45a819bfd46f2e1fL, DomainClass);
    builder.put(0x7890b7ca77f4c4c1L, Target);
    builder.put(0x7890b7ca77f86665L, TargetCommand);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
