package ZES.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ActCommandHandler_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Command_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new CommandHandler_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ActCommandHandler_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new Command_SubstituteMenu());
      case 2:
        return Collections.<SubstituteMenu>singletonList(new CommandHandler_SubstituteMenu());
      case 3:
        return Collections.<SubstituteMenu>singletonList(new CreateCommand_SubstituteMenu());
      case 4:
        return Collections.<SubstituteMenu>singletonList(new CreateCommandHandler_SubstituteMenu());
      case 5:
        return Collections.<SubstituteMenu>singletonList(new QueryHandler_SubstituteMenu());
      case 6:
        return Collections.<SubstituteMenu>singletonList(new TargetCommand_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x7890b7ca7815b52bL), MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x45a819bfd46f2e3aL), MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x7890b7ca7815b026L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x7890b7ca7815b52bL), MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x45a819bfd46f2e3aL), MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x7890b7ca7815b026L), MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x7890b7ca78198eb0L), MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x7890b7ca7815b52cL), MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x7890b7ca78d75a70L), MetaIdFactory.conceptId(0xabe666e11ee143feL, 0x93c4703403beeec8L, 0x7890b7ca77f86665L)).seal();
}
